version: "3.9"

x-app: &app
  env_file:
    - ./.env
  restart: always

services:
  auth-api:
    build:
      context: ./api_grpc_server
    <<: *app
    volumes:
      - ./api_grpc_server:/usr/src/app/
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - auth-database

  auth-grpc:
    build:
      context: ./api_grpc_server
    <<: *app
    volumes:
      - ./api_grpc_server:/usr/src/app/
    environment:
      - RUN_MODE=GRPC
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - auth-database

  auth-database:
    image: postgres:14
    <<: *app
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    ports:
      - "54320:5432"

  admin-database:
    image: postgres:14
    <<: *app
    volumes:
      - admin_db_data:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "54321:5432"

  admin-django:
    build:
      context: ./adminka
    <<: *app
    volumes:
      - ./adminka:/usr/src/app/
    depends_on:
      admin-database:
        condition: service_healthy
    ports:
      - "8081:8000"

  auth-redis:
    image: redis:6.0-alpine
    volumes:
      - auth_redis_volume:/data
    <<: *app
    command:
      - "redis-server"
      - "--databases 2"
      - "--save 900 1"
      - "--save 300 10"
      - "--save 60 10000"
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:auth-redis:6379
    ports:
      - "8090:8081"

  simple_api:
    build:
      context: ./api_simple
    <<: *app
    volumes:
      - ./api_simple:/usr/src/app/
    ports:
      - "8085:8085"
    depends_on:
      - auth-database

volumes:
  auth_db_data:
  auth_redis_volume:
  admin_db_data:
