# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0busers.proto"\x14\n\x12GetAllUsersRequest"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t"%\n\x16GetMultipleUserRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t"\x85\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t"4\n\x14MultipleUserResponse\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.UserResponse2\xc2\x01\n\x08\x44\x65tailer\x12/\n\x0b\x44\x65tailsById\x12\x0f.GetUserRequest\x1a\r.UserResponse"\x00\x12H\n\x14MultipleDetailsByIds\x12\x17.GetMultipleUserRequest\x1a\x15.MultipleUserResponse"\x00\x12;\n\x0bGetAllUsers\x12\x13.GetAllUsersRequest\x1a\x15.MultipleUserResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _GETALLUSERSREQUEST._serialized_start = 15
    _GETALLUSERSREQUEST._serialized_end = 35
    _GETUSERREQUEST._serialized_start = 37
    _GETUSERREQUEST._serialized_end = 65
    _GETMULTIPLEUSERREQUEST._serialized_start = 67
    _GETMULTIPLEUSERREQUEST._serialized_end = 104
    _USERRESPONSE._serialized_start = 107
    _USERRESPONSE._serialized_end = 240
    _MULTIPLEUSERRESPONSE._serialized_start = 242
    _MULTIPLEUSERRESPONSE._serialized_end = 294
    _DETAILER._serialized_start = 297
    _DETAILER._serialized_end = 491
# @@protoc_insertion_point(module_scope)
